const works = [
    { author: "Micheal Jackson",lifetime:"1022-1055",tips: "Human", photos: ["human1.jpg","human2.jpg","human3.jpg"] },
    { author: "Maria JK",lifetime:"1920-2001", tips: "Classical", photos: ["classical1.jpg","classical2.jpg"] },
    { author: "John Herry UY", lifetime:"1894-1928",tips: "Abstract", photos: ["abstract1.jpg","abstract2.jpg","abstract3.jpg","abstract4.jpg","abstract5.jpg"] },
    { author: "Coco",lifetime:"1777-1799", tips: "Beauty",  photos: ["beauty1.jpg","beauty2.jpg"] }
];
var newNode = document.createElement("div");
newNode.className = "justify";
document.body.appendChild(newNode);
var newNode1 = document.createElement("div");
newNode1.className = "item";
var newNode11 = document.createElement("p");
var newNode111 = document.createElement("span");
newNode111.innerText = "Genre:Human";
newNode11.appendChild(newNode111);
newNode1.appendChild(newNode11);
var newNode12 = document.createElement("h3");
newNode12.className = "inner-box";
var newNode121 = document.createElement("span");
newNode121.innerText = "Micheal Jackson ";
var newNode122 = document.createElement("span");
newNode122.innerText = " life-time:1022-1055";
newNode122.style.fontSize = "12pt";
newNode12.appendChild(newNode121);
newNode12.appendChild(newNode122);
newNode1.appendChild(newNode12);
var newNode13 = document.createElement("h3");
newNode13.className = "inner-box";
var newNode131 = document.createElement("h3");
newNode131.innerText = "Popular Photos";
newNode13.appendChild(newNode131);
var newNode132 = document.createElement("img");
newNode132.className = "photo";
newNode132.src = "./human1.jpg";
newNode13.append(newNode132);
var newNode133 = document.createElement("img");
newNode133.className = "photo";
newNode133.src = "./human2.jpg";
newNode13.append(newNode133);
var newNode134 = document.createElement("img");
newNode134.className = "photo";
newNode134.src = "./human3.jpg";
newNode13.append(newNode134);
newNode1.appendChild(newNode13);
var newNode14 = document.createElement("button");
newNode14.innerText = "visit";
newNode1.appendChild(newNode14);
newNode.appendChild(newNode1);


var newNode2 = document.createElement("div");
newNode2.className = "item";
var newNode21 = document.createElement("p");
var newNode211 = document.createElement("span");
newNode211.innerText = "Genre:Classical";
newNode21.appendChild(newNode211);
newNode2.appendChild(newNode21);
var newNode22 = document.createElement("h3");
newNode22.className = "inner-box";
var newNode221 = document.createElement("span");
newNode221.innerText = "Maria JK ";
var newNode222 = document.createElement("span");
newNode222.innerText = " life-time:1920-2001";
newNode222.style.fontSize = "12pt";
newNode22.appendChild(newNode221);
newNode22.appendChild(newNode222);
newNode2.appendChild(newNode22);
var newNode23 = document.createElement("h3");
newNode23.className = "inner-box";
var newNode231 = document.createElement("h3");
newNode231.innerText = "Popular Photos";
newNode23.appendChild(newNode231);
var newNode232 = document.createElement("img");
newNode232.className = "photo";
newNode232.src = "./classical1.jpg";
newNode23.append(newNode232);
var newNode233 = document.createElement("img");
newNode233.className = "photo";
newNode233.src = "./classical2.jpg";
newNode23.append(newNode233);
newNode2.appendChild(newNode23);
var newNode24 = document.createElement("button");
newNode24.innerText = "visit";
newNode2.appendChild(newNode24);
newNode.appendChild(newNode2);


var newNode3 = document.createElement("div");
newNode3.className = "item";
var newNode31 = document.createElement("p");
var newNode311 = document.createElement("span");
newNode311.innerText = "Genre:Abstract";
newNode31.appendChild(newNode311);
newNode3.appendChild(newNode31);
var newNode32 = document.createElement("h3");
newNode32.className = "inner-box";
var newNode321 = document.createElement("span");
newNode321.innerText = "John Herry UY ";
var newNode322 = document.createElement("span");
newNode322.innerText = " life-time:1894-1928";
newNode322.style.fontSize = "12pt";
newNode32.appendChild(newNode321);
newNode32.appendChild(newNode322);
newNode3.appendChild(newNode32);
var newNode33 = document.createElement("h3");
newNode33.className = "inner-box";
var newNode331 = document.createElement("h3");
newNode331.innerText = "Popular Photos";
newNode33.appendChild(newNode331);
var newNode332 = document.createElement("img");
newNode332.className = "photo";
newNode332.src = "./abstract1.jpg";
newNode33.append(newNode332);
var newNode333 = document.createElement("img");
newNode333.className = "photo";
newNode333.src = "./abstract2.jpg";
newNode33.append(newNode333);
var newNode334 = document.createElement("img");
newNode334.className = "photo";
newNode334.src = "./abstract3.jpg";
newNode33.append(newNode334);
var newNode335 = document.createElement("img");
newNode335.className = "photo";
newNode335.src = "./abstract4.jpg";
newNode33.append(newNode335);
var newNode336 = document.createElement("img");
newNode336.className = "photo";
newNode336.src = "./abstract5.jpg";
newNode33.append(newNode336);
newNode3.appendChild(newNode33);
var newNode34 = document.createElement("button");
newNode34.innerText = "visit";
newNode3.appendChild(newNode34);
newNode.appendChild(newNode3);


var newNode4 = document.createElement("div");
newNode4.className = "item";
var newNode41 = document.createElement("p");
var newNode411 = document.createElement("span");
newNode411.innerText = "Genre:Beauty";
newNode41.appendChild(newNode411);
newNode4.appendChild(newNode41);
var newNode42 = document.createElement("h3");
newNode42.className = "inner-box";
var newNode421 = document.createElement("span");
newNode421.innerText = "Coco ";
var newNode422 = document.createElement("span");
newNode422.innerText = " life-time:1777-1799";
newNode422.style.fontSize = "12pt";
newNode42.appendChild(newNode421);
newNode42.appendChild(newNode422);
newNode4.appendChild(newNode42);
var newNode43 = document.createElement("h3");
newNode43.className = "inner-box";
var newNode431 = document.createElement("h3");
newNode431.innerText = "Popular Photos";
newNode43.appendChild(newNode431);
var newNode432 = document.createElement("img");
newNode432.className = "photo";
newNode432.src = "./beauty1.jpg";
newNode43.append(newNode432);
var newNode433 = document.createElement("img");
newNode433.className = "photo";
newNode433.src = "./beauty2.jpg";
newNode43.append(newNode433);
newNode4.appendChild(newNode43);
var newNode44 = document.createElement("button");
newNode44.innerText = "visit";
newNode4.appendChild(newNode44);
newNode.appendChild(newNode4);
